version: "3"
services:
    jenkins:
        #docker build -t jenkins/jenkins:lts https://github.com/jenkinsci/docker.git
        image: rpi-jenkins:latest
        deploy:
            replicas: 1
        ports:
            - "8080:8080"
            - "5000:5000"
        volumes:
            - jenkins_home:/var/jenkins_home

    visualizer:
        image: alexellis2/visualizer-arm
        deploy:
            replicas: 1
            placement:
                constraints:
                    - node.role == manager
        ports:
            - "8000:8080"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock

volumes:
    jenkins_home: