version: '3'
services:
    jenkins:
        build: ./
        dockerfile: Dockerfile
        ports:
            - "7070:8080"
            - "5000:5000"
        volumes:
            - jenkins_home:/var/jenkins_home
