version: "3"
services:
    jenkins:
        image: vargaf68/rpi-jenkins:latest
        deploy:
            replicas: 1
        ports:
            - "8080:8080"
            - "5000:5000"
        volumes:
            - jenkins_home:/var/jenkins_home

    visualizer:
        image: alexellis2/visualizer-arm
        deploy:
            replicas: 1
            placement:
                constraints:
                    - node.role == manager
        ports:
            - "8000:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

    cdmon:
        container_name: cdmon
        image: pferraris/docker-cdmon
        restart: always
        environment:
            CDMON_DOMAIN: warcommands.com
            CDMON_USERNAME: vargaf68
            CDMON_PASSWORD: 6e8db8fbca9b07d0c753ccca017a4a6d
            CDMON_INTERVAL: 1800000

volumes:
    jenkins_home: