version: "3"
services:
    jenkins:
        image: jenkins/jenkins:lts
        ports:
            - "8080:8080"
            - "5000:5000"
        volumes:
            - jenkins_home:/var/jenkins_home

    visualizer:
        image: visualizer-arm:latest
        deploy:
              placement:
                  constraints:
                      - node.role == manager
        ports:
            - "8000:8080"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock

volumes:
    jenkins_home: